@startuml

class Repository << (S,#FF7700) Singleton >>
class Repository
    note right: Dependency Injection \n using Dagger2

package RoomDatabase <<Database>> {
}

MainActivity  --*  MainFragment : contains
MainActivity  --*  ReportFragment : contains
ReportFragment --* ReportViewModel :  contains
EditFragment --* EditViewModel :  contains
MainActivity  --*  EditFragment : contains

EditFragment <..> EditViewModel :  LiveData
ReportFragment <..> ReportViewModel :  LiveData
MainFragment <..> MainViewModel : LiveData
MainFragment --* MainViewModel : contains

ReportViewModel --* Repository : contains
MainViewModel --* Repository : contains
EditViewModel --* Repository : contains

Repository --* RoomDatabase: contains


@enduml