@startuml
actor user

box "app"
participant manager
database database
endbox

user -> manager : open
manager --> user : main screen

alt save new
user -> manager : click on save button
manager -> database : save item
end

alt generate report
user -> manager : click on report button
manager --> user : choose date screen
user -> manager : choose date
manager -> database : fetch data {date}
database --> manager : data {List}
manager --> manager : format data
manager --> user : report of the day
end

alt edit item
manager --> user : report of the day
user -> manager : click on edit on item
manager --> user : edit screen
user -> manager : new values of item
manager --> manager : validate values
manager -> database : new values of item
database --> database : persist
database --> manager : data {List}
manager --> manager : format data
manager --> user : report of the day
end

alt delete item
manager --> user : report of the day
user -> manager : click on delete on item
manager -> database : delete item
database --> database : persist
database --> manager : data {List}
manager --> manager : format data
manager --> user : report of the day
end

@enduml